# Name:         Midnight Sea Dragon
# Author:       DireTabacchi
# Maintainer:   DireTabacchi
# Last change:  2023 02 04

# UI Theming =========================================================

# General UI
"ui.background" = {bg = "dark0"}
"ui.background.separator" = {fg = "blue", bg = "black"}
"ui.selection" = {fg = "dark0", bg = "orange"}
"ui.cursor" = {fg = "dark0", bg = "color-cursor"}

# Cursor
"ui.cursor.insert" = {fg = "dark0", bg = "color-cursor"}
"ui.cursor.select" = {fg = "dark0", bg = "light-orange"}
"ui.cursor.match" = {fg = "light-cyan", modifiers = ["bold"]}
#"ui.cursor.primary" = {fg = "dark0", bg = "color-cursor"}

# Gutter
"ui.gutter" = {fg = "white", bg = "dark1"}
"ui.gutter.selected" = {fg = "light-white", bg = "dark5"}
"ui.linenr" = {fg = "white", bg = "dark1"}
"ui.linenr.selected" = {fg = "yellow", bg = "dark5"}

# Statusline
"ui.statusline" = {fg = "light0", bg = "light-black"}
"ui.statusline.inactive" = {fg = "white", bg = "black"}
"ui.statusline.normal" = {fg = "light0", bg = "blue"}
"ui.statusline.insert" = {fg = "dark0", bg = "light-green"}
"ui.statusline.select" = {fg = "dark0", bg = "light-orange"}
"ui.statusline.separator" = {fg = "white"}

# Popups
"ui.popup" = {fg = "white", bg = "light-black"}
"ui.popup.info" = {fg = "blue", bg = "black"}
"ui.window" = {fg = "white", bg = "light-black"}
"ui.help" = {fg = "blue", bg = "black"}
"ui.text" = "light0"
"ui.text.focus" = "light0"
# What does this actually change?
"ui.text.inactive" = {fg = "red", bg = "purple"}
"ui.text.info" = {fg = "white", bg = "black"}
"ui.virtual.ruler" = {fg = "light0", bg = "light-black"}
"ui.virtual.whitespace" = {modifiers = ["hidden"]}
"ui.virtual.indent-guide" = {fg = "dark3", bg = "dark0"}
"ui.menu" = {fg = "white", bg = "dark1"}
"ui.menu.selected" = {fg = "light-white", bg = "light-orange"}
"ui.menu.scroll" = {fg = "white", bg = "dark3"}
"ui.selection.primary" = {fg = "dark0", bg = "light-orange"}
"ui.cursorline.primary" = {bg = "dark2"}
"ui.cursorline.secondary" = {fg = "", bg = "dark1"}
"ui.cursorcolumn.primary" = {fg = "", bg = "dark1"}
"ui.cursorcolumn.secondary" = {fg = "", bg = "dark1"}
"error" = {fg = "light-red", bg = "black"}
# TODO:
"warning" = {fg = "light-yellow"}
"info" = {fg = "light-cyan", bg = "black"}
"hint" = {fg = "light-cyan", bg = "black"}
"diagnostic" = {bg = "dark0", modifiers = ["underlined"]}
# Uncomment diagnostic.error and diagnostic.warning for agressive diagnostics
#"diagnostic.error" = {fg = "dark0", bg = "light-red"}
#"diagnostic.warning" = {fg = "light-yellow", bg = "dark1", modifiers = ["underlined"]}
"diagnostic.info" = {modifiers = ["underlined"]}
"diagnostic.hint" = {modifiers = ["underlined"]}

# Markup -------------------------------------------------------------

"markup.heading.marker" = "white"
"markup.heading.1" = {fg = "light-red", modifiers = ["bold"]}
"markup.heading.2" = {fg = "yellow", modifiers = ["bold"]}
"markup.heading.3" = {fg = "light-yellow", modifiers = ["bold"]}
"markup.heading.4" = {fg = "light-green", modifiers = ["bold"]}
"markup.heading.5" = {fg = "light-blue", modifiers = ["bold"]}
"markup.heading.6" = {fg = "light-purple", modifiers = ["bold"]}
"markup.list" = "white"
"markup.bold" = {fg = "light-blue", modifiers = ["bold"]}
"markup.italic" = {fg = "light-green", modifiers = ["italic"]}
"markup.link" = "light-cyan"
"markup.link.url" = "light-cyan"
"markup.link.label" = "light-blue"
"markup.link.text" = "light-blue"
"markup.quote" = "blue"
"markup.raw" = {fg = "blue", bg = "dark1"}
"markup.normal" = {fg = "red", bg = "yellow"}

# End UI Theming =====================================================

# Syntax Highlighting ================================================

"attribute" = "red"

# Types
"type" = "cyan"
"type.builtin" = "light-cyan"

# Function related
"function" = "yellow"

# Constants
"constant" = "light-green"
"constant.builtin" = "light-purple"
"constant.character" = "light-yellow"
"constant.character.escape" = "light-yellow"
"constant.numeric" = "light-purple"
"string" = "light-green"

# Comments
"comment" = "white"
"comment.block" = "light-orange"

"variable" = "light-blue"
"label" = "light-yellow"

# Punctuation
"punctuation" = "light-white"

# Keywords
"keyword" = "light-red"
"keyword.storage.modifier.mut" = "light-purple"
"keyword.storage.modifier.ref" = "light-yellow"
"keyword.directive" = "purple"

"operator" = "light-yellow"
"tag" = "red"
"namespace" = "green"
"special" = "light-purple"

# End Syntax Highlighting ============================================

# Palette ============================================================

[palette]
# Sixteen-Color Palette ----------------------------------------------
# Dark Colors
black =     "#030b1a"
red =       "#b31212"
green =     "#169908"
yellow =    "#de591c"
blue =      "#1369bf"
purple =    "#bf0abf"
cyan =      "#0ab6bf"
white =     "#828b99"

# Light Colors
light-black =   "#262f3f"
light-red =     "#f23030"
light-green =   "#31d821"
light-yellow =  "#f2dd00"
light-blue =    "#3399ff"
light-purple =  "#ff27ff"
light-cyan =    "#26f8fe"
light-white =   "#f3ffff"

# Other Color Definitions --------------------------------------------
dark0 = "#01040d"
dark1 = "#050a1a"
dark2 = "#0b1226"
dark3 = "#131b33"
dark4 = "#1f2740"
dark5 = "#2c344d"
light0 = "#ffffff"
light1 = "#dadde6"
light2 = "#b8bdcc"
light3 = "#989eb3"
light4 = "#7a8299"
light5 = "#606880"
color-cursor = "#828b99"
orange = "#bf5726"
light-orange = "#d95316"

# End Palette ========================================================
